export const TipoNotificacion = Object.freeze({
  RESERVA_TURNO: 'RESERVA_TURNO',
  TURNO_ACEPTADO: 'TURNO_ACEPTADO',
  CANCELACION_PACIENTE: 'CANCELACION_PACIENTE',
  CANCELACION_MEDICO: 'CANCELACION_MEDICO',
  MODIFICACION_TURNO: 'MODIFICACION_TURNO',
  RECORDATORIO: 'RECORDATORIO',
});
